apiVersion: appcat.vshn.io/v1alpha1
kind: XVSHNRedis
metadata:
  name: my-redis-1
  namespace: default
spec:
  writeConnectionSecretToRef:
    name: redis-credentials-1
    namespace: default
  size:
    cpu: "1000m"
    memory: "4Gi"
    disk: "16Gi"
  replicas: 1