apiVersion: appcat.vshn.io/v1alpha1
kind: XVSHNRedis
metadata:
  name: my-redis
  namespace: default
spec:
  size:
    cpu: "1000m"
    memory: "4Gi"
    disk: "16Gi"
  replicas: 3
# Note: Connection details are automatically created as a Secret named {instance-name}-connection